swagger: "2.0"
info:
    title: Calculator Service
    description: Service for multiplying numbers, a Goa teaser
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /multiply:
        post:
            tags:
                - calc
            summary: multiply calc
            operationId: calc#multiply
            parameters:
                - name: MultiplyRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/CalcMultiplyRequestBody'
                    required:
                        - a
                        - b
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CalcMultiplyResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - calc
            summary: Download ./gen/http/openapi.json
            operationId: calc#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    CalcMultiplyRequestBody:
        title: CalcMultiplyRequestBody
        type: object
        properties:
            a:
                type: integer
                description: Left operand
                example: 3219793201326175278
                format: int64
            b:
                type: integer
                description: Right operand
                example: 8803302123552712831
                format: int64
        example:
            a: 5401762099778430809
            b: 1918630006328122782
        required:
            - a
            - b
    CalcMultiplyResponseBody:
        title: 'Mediatype identifier: multiplyresponse; view=default'
        type: object
        properties:
            multiple:
                type: integer
                description: Result of multiplication
                example: 360622074634248926
                format: int64
        description: MultiplyResponseBody result type (default view)
        example:
            multiple: 8133055152903002499
        required:
            - multiple
